import { ArrowDown, ArrowUpRight, BrainCircuit, Check, FileText, Layers3, Network, Sparkles } from 'lucide-react';
import { Navbar } from '@/components/Navbar';
import { ProjectGrid } from '@/components/ProjectGrid';
import { HeroSystemVisual } from '@/components/SystemVisual';
import { projects } from '@/data/projects';
import { coreSkills, skillGroups } from '@/data/skills';
import { education, experience } from '@/data/experience';
import { social } from '@/data/social';
import { Reveal } from '@/components/Reveal';

function SectionHeading({ index, title, text }: { index: string; title: string; text?: string }) {
  return <div className="mb-8 flex flex-col gap-3 md:flex-row md:items-end md:justify-between"><div><p className="section-kicker">{index}</p><h2 className="mt-4 font-display text-3xl font-medium tracking-[-.05em] text-white md:text-5xl">{title}</h2></div>{text && <p className="max-w-md text-sm leading-6 text-muted">{text}</p>}</div>;
}

function Timeline({ items }: { items: typeof experience }) {
  return <div className="timeline-line space-y-7">{items.map((item) => <article key={`${item.title}-${item.period}`} className="timeline-item"><p className="text-[11px] uppercase tracking-[.13em] text-signal">{item.period}</p><h3 className="mt-2 font-display text-xl text-white">{item.title}</h3>{item.organisation && <p className="mt-1 text-sm text-muted">{item.organisation}</p>}{item.description && <p className="mt-3 text-sm leading-6 text-muted">{item.description}</p>}{item.details && <ul className="mt-4 grid gap-2 sm:grid-cols-2">{item.details.map((detail) => <li key={detail} className="flex gap-2 text-xs leading-5 text-muted"><Check size={13} className="mt-1 shrink-0 text-signal" />{detail}</li>)}</ul>}</article>)}</div>;
}

export default function Home() {
  const aiSystems = projects.filter((project) => project.featured);
  const mlProjects = projects.filter((project) => project.category === 'Machine Learning');
  const github = social.links.find((link) => link.label === 'GitHub');
  const linkedIn = social.links.find((link) => link.label === 'LinkedIn');
  return <main id="top"><Navbar />
    <section className="shell relative grid gap-10 overflow-hidden pb-16 pt-16 lg:grid-cols-[.9fr_1.1fr] lg:items-center lg:gap-16 lg:pb-24 lg:pt-24">
      <div className="hero-glow pointer-events-none absolute -left-32 -top-40 h-[34rem] w-[34rem] rounded-full blur-3xl" />
      <div className="relative z-10"><p className="eyebrow text-xs md:text-[13px]">Ritik Mishra <span className="ml-2 text-muted">/ portfolio 2026</span></p><h1 className="mt-6 max-w-3xl font-display text-[3.6rem] font-medium leading-[.94] tracking-[-.075em] text-white sm:text-7xl lg:text-[6.4rem]">GenAI &amp;<br /><span className="text-signal">Agentic AI</span><br />Developer</h1><p className="mt-7 max-w-xl text-base leading-7 text-muted md:text-lg">I build intelligent applications using LLMs, RAG, AI agents, tool calling and modern AI engineering workflows.</p><div className="mt-8 flex flex-wrap gap-3"><a href="#projects" className="button-primary">Explore Work <ArrowDown size={15} /></a>{github?.href && <a href={github.href} target="_blank" rel="noreferrer" className="button-secondary">GitHub <ArrowUpRight size={15} /></a>}{linkedIn?.href && <a href={linkedIn.href} target="_blank" rel="noreferrer" className="button-secondary">LinkedIn <ArrowUpRight size={15} /></a>}{social.resumeUrl && <a href={social.resumeUrl} className="button-secondary">Resume <FileText size={15} /></a>}</div><div className="mt-10 flex items-center gap-3 text-[11px] uppercase tracking-[.15em] text-muted"><span className="live-dot" />Building at the intersection of models and software</div></div>
      <Reveal><HeroSystemVisual /></Reveal>
    </section>

    <section className="border-y border-line bg-panel/35"><div className="shell py-12 md:py-16"><div className="mb-7 flex items-end justify-between"><div><p className="section-kicker">00 / What I build</p><h2 className="mt-3 font-display text-2xl tracking-[-.04em] text-white md:text-3xl">AI engineering focus</h2></div><Sparkles className="text-signal" size={20} /></div><div className="grid gap-3 md:grid-cols-3"><article className="focus-card"><BrainCircuit className="text-signal" size={20} /><h3>Generative AI</h3><p>LLM applications, RAG systems, and grounded generation that turn model capability into useful interfaces.</p></article><article className="focus-card"><Network className="text-signal" size={20} /><h3>Agentic AI</h3><p>LangGraph, tool calling, MCP, and human-in-the-loop workflows for systems that can act with control.</p></article><article className="focus-card"><Layers3 className="text-signal" size={20} /><h3>AI engineering</h3><p>APIs, workflows, deployment, and stateful applications built around practical delivery.</p></article></div></div></section>

    <section id="projects" className="shell scroll-mt-20 py-16 md:py-20"><Reveal><SectionHeading index="01 / Selected work" title="AI systems I’ve built" text="Four different ways to make intelligence useful: coding, retrieval, writing, and tools." /><ProjectGrid projects={aiSystems} featured /></Reveal></section>
    <section className="shell py-16 md:py-20"><Reveal><SectionHeading index="02 / Supporting foundation" title="Machine learning projects" text="A compact foundation across NLP, classification, recommendations, and regression." /><ProjectGrid projects={mlProjects} /></Reveal></section>

    <section id="skills" className="border-y border-line bg-panel/35 scroll-mt-20"><div className="shell py-16 md:py-20"><SectionHeading index="03 / AI stack" title="AI stack & capabilities" text="The tools and systems I use to build LLM applications, agentic workflows, and practical AI products." /><div className="grid items-stretch gap-3 sm:grid-cols-2 lg:grid-cols-4">{skillGroups.map((group, index) => <article key={group.label} className={`flex h-full flex-col rounded-xl border p-5 transition hover:-translate-y-1 ${index < 2 ? 'border-signal/30 bg-signal/[.045] hover:border-signal/60' : index === 2 ? 'border-line bg-ink/70 hover:border-signal/40' : 'border-line/70 bg-ink/45 opacity-85 hover:border-line'}`}><div className="flex items-center justify-between"><span className={`text-[10px] ${index < 2 ? 'text-signal' : 'text-muted'}`}>0{index + 1}</span><span className={`h-1.5 w-1.5 rounded-full ${index < 2 ? 'bg-signal shadow-[0_0_10px_rgba(198,255,77,.7)]' : 'bg-muted/60'}`} /></div><h3 className={`mt-8 whitespace-normal font-display text-lg text-white ${index === 3 ? 'tracking-normal' : 'tracking-[-.02em]'}`}>{group.label}</h3><ul className="mt-5 space-y-2">{group.skills.map((skill) => <li key={skill} className="border-t border-line/80 pt-2 text-xs leading-5 text-muted">{skill}</li>)}</ul></article>)}</div><div className="mt-4 flex flex-wrap items-center gap-x-4 gap-y-2 rounded-xl border border-line/70 bg-ink/35 px-5 py-4"><span className="text-[10px] font-medium uppercase tracking-[.18em] text-signal">CORE</span><span className="hidden text-line sm:inline">/</span>{coreSkills.map((skill, index) => <span key={skill} className="text-xs text-muted">{skill}{index < coreSkills.length - 1 && <span className="ml-4 text-line">·</span>}</span>)}</div></div></section>

    <section id="background" className="shell scroll-mt-20 py-16 md:py-20"><SectionHeading index="04 / Background" title="Experience & education" text="The verified foundation behind the work." /><div className="grid gap-12 lg:grid-cols-[1.3fr_.7fr]"><Timeline items={experience} /><div><p className="eyebrow">Education</p><div className="mt-5 rounded-xl border border-line bg-panel p-5"><p className="text-[11px] uppercase tracking-[.13em] text-signal">{education[0]?.period}</p><h3 className="mt-3 font-display text-xl text-white">{education[0]?.title}</h3><p className="mt-1 text-sm text-muted">{education[0]?.organisation}</p><p className="mt-6 border-t border-line pt-4 text-sm text-muted">{education[0]?.description}</p></div></div></div></section>

    <section id="contact" className="scroll-mt-20 border-y border-line"><div className="shell grid gap-8 py-16 md:grid-cols-[1fr_auto] md:items-end md:py-20"><div><p className="section-kicker">05 / Contact</p><h2 className="mt-4 max-w-2xl font-display text-4xl font-medium tracking-[-.06em] text-white md:text-6xl">Have an interesting AI problem?<br /><span className="text-signal">Let’s build something useful.</span></h2><p className="mt-5 text-sm text-muted">{social.email} <span className="mx-2 text-line">·</span> {social.phone}</p></div><div className="flex flex-wrap gap-3"><a href={`mailto:${social.email}`} className="button-primary">Email Me <ArrowUpRight size={15} /></a>{linkedIn?.href && <a href={linkedIn.href} target="_blank" rel="noreferrer" className="button-secondary">LinkedIn <ArrowUpRight size={15} /></a>}{github?.href && <a href={github.href} target="_blank" rel="noreferrer" className="button-secondary">GitHub <ArrowUpRight size={15} /></a>}</div></div></section>
    <footer className="border-t border-line"><div className="shell flex flex-col gap-3 py-6 text-xs text-muted sm:flex-row sm:justify-between"><span>Ritik Mishra / GenAI &amp; Agentic AI Developer</span><span>Built for practical AI systems.</span></div></footer>
  </main>;
}
